---
- name: Install Wordpress & MySQL
  hosts: all
  vars:
    wp_dir: /opt/wordpress
    wp_git_repository: https://github.com/oesteve/wordpress.git
  tasks:


    - name: Create WP dirs
      file:
        path: "{{ wp_dir }}"
        state: directory
        mode: 0755
        owner: 33 # www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
        group: 33

    - name: Create WP dirs
      file:
        path: "{{ wp_dir }}/{{ item }}"
        state: directory
        mode: 0755
        owner: 33 # www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
        group: 33
      with_items:
        - db
        - plugins
        - uploads
        - html

    - name: Run docker mysql image
      docker_container:
        name: mysql
        state: started
        image: mysql:5.7
        restart_policy: always
        restart: true
        published_ports:
          - "3306:3306"
        env:
          MYSQL_DATABASE: wp
          MYSQL_USER: wp_user
          MYSQL_PASSWORD: wp_password
          MYSQL_RANDOM_ROOT_PASSWORD: wp_root_password
        volumes:
           - "{{ wp_dir }}/db:/var/lib/mysql/"

    - name: Run docker wp image
      docker_container:
        name: wordpress
        state: started
        image: wordpress
        restart: true
        restart_policy: always
        published_ports:
          - "8088:80"
        env:
          WORDPRESS_DB_HOST: "{{ ansible_default_ipv4.address }}"
          WORDPRESS_DB_USER: wp_user
          WORDPRESS_DB_PASSWORD: wp_password
          WORDPRESS_DB_NAME: wp
        volumes:
          - "{{ wp_dir }}/plugins:/var/www/html/wp-content/plugins"
          - "{{ wp_dir }}/uploads:/var/www/html/wp-content/uploads"

