---
- name: Install Nginx Http 2.0 with Let's Encrypt
  hosts: all
  vars:
    backends:
      - name: oscaresteve.com
        hostnames:
          - oscaresteve.com
          - www.oscaresteve.com
        servers:
          - 172.17.0.1:8088
  roles:
    - ansible-docker-nginx
